### ISSUE TITLE
Sometimes slower than npx kill-port

### ISSUE THREAD

**Issue by wingleeio** [SinaKhalili/zshutils#1]
title

**Comment by SinaKhalili** [comment]
Could you please carify? Your description is a bit terse

**Comment by wingleeio** [comment]
Why would I use this when npx kill-port kills port faster

**Comment by SinaKhalili** [comment]
I benchmarked it on my M1 Max Macbook PRO (2 terabytes) and I'm getting <1 second on `killport` and 5+ seconds on `npx killport`. Could you send me your stats in a docker container?
